/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.9.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *Menu_system;
    QAction *Menu_Score;
    QAction *Menu_print;
    QAction *Menu_add_student;
    QAction *Menu_delete_student;
    QAction *Menu_change_student;
    QAction *Menu_find_student;
    QAction *Menu_add_course;
    QAction *Menu_delete_course;
    QAction *Menu_change_course;
    QAction *Menu_find_course;
    QAction *Menu_exit;
    QAction *File_save;
    QWidget *centralWidget;
    QStackedWidget *stackedWidget;
    QWidget *page;
    QWidget *Registerwidget;
    QLabel *label;
    QLabel *label_2;
    QLineEdit *Register_idLineEdit;
    QLineEdit *Register_passwardLineEdit;
    QLabel *label_3;
    QLineEdit *Register_checkedWard_lineEdit;
    QPushButton *btn_Register_checked;
    QPushButton *btn_register_return;
    QWidget *page_2;
    QWidget *Loginwidget;
    QLineEdit *Login_idLineEdit;
    QLineEdit *Login_passwardLineEdit;
    QLabel *idLabel;
    QLabel *passwardLabel;
    QPushButton *btn_login;
    QPushButton *btn_register;
    QWidget *page_3;
    QWidget *Systemwidget;
    QPushButton *btn_addstudent;
    QPushButton *btn_deletestudent;
    QPushButton *btn_changepassward;
    QPushButton *btn_SystemReturnToLogin;
    QWidget *page_4;
    QLabel *label_17;
    QComboBox *Course_id_comboBox;
    QLabel *label_18;
    QLabel *Course_name_label;
    QLabel *label_20;
    QLabel *Course_class_label;
    QLabel *label_22;
    QComboBox *Course_select_comboBox;
    QPushButton *btn_Course_checked;
    QWidget *page_5;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLineEdit *Addstudnet_id_LineEdit;
    QLineEdit *Addstudent_name_LineEdit;
    QLineEdit *Addstudent_sex_LineEdit;
    QLineEdit *Addstudent_class_LineEdit;
    QPushButton *btn_student_add;
    QWidget *page_6;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *Find_student_nameLabel;
    QLabel *Find_student_sexLabel;
    QLabel *Find_student_classLabel;
    QPushButton *btn_Find_student;
    QComboBox *Find_student_comboBox;
    QWidget *page_7;
    QComboBox *delete_student_comboBox;
    QLabel *label_12;
    QPushButton *btn_student_delete;
    QWidget *page_8;
    QLabel *label_13;
    QComboBox *change_student_comboBox;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLineEdit *change_student_namelineEdit;
    QLineEdit *change_student_sexlineEdit;
    QLineEdit *change_student_classlineEdit;
    QPushButton *btn_change_student;
    QWidget *page_9;
    QLabel *label_19;
    QLabel *label_21;
    QLabel *label_23;
    QLabel *label_24;
    QComboBox *Course_delete_idcomboBox;
    QLabel *Course_delete_namelabel;
    QLabel *Course_delete_classlabel;
    QComboBox *Course_delete_selectcomboBox;
    QPushButton *btn_course_delete;
    QWidget *page_11;
    QLabel *label_25;
    QComboBox *Course_Find_comboBox;
    QPushButton *btn_Course_Find;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *Course_Find_label_highmath;
    QLabel *Course_Find_label_posmath;
    QLabel *Course_Find_label_linearMath;
    QLabel *Course_Find_label_discreteMath;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *Course_Find_label_cplus2;
    QLabel *Course_Find_label_java;
    QLabel *Course_Find_label_python;
    QWidget *page_12;
    QLabel *label_30;
    QComboBox *Score_id_comboBox;
    QLabel *label_31;
    QLabel *Score_name_label;
    QLabel *label_33;
    QLabel *Score_class_label;
    QLabel *label_38;
    QLineEdit *Score_lineEdit_highMath;
    QLabel *label_39;
    QLineEdit *Score_lineEdit_posMath;
    QLabel *label_40;
    QLineEdit *Score_lineEdit_linearMath;
    QLabel *label_41;
    QLineEdit *Score_lineEdit_discreteMath;
    QLabel *label_42;
    QLineEdit *Score_lineEdit_cplus2;
    QLabel *label_43;
    QLineEdit *Score_lineEdit_java;
    QLabel *label_44;
    QLineEdit *Score_lineEdit_python;
    QWidget *page_10;
    QMenuBar *menuBar;
    QMenu *menu;
    QMenu *Menu_Student;
    QMenu *Menu_course;
    QMenu *menu_2;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(534, 467);
        MainWindow->setStyleSheet(QStringLiteral("border-image: url(:/Image/t012da561733aa69511[1].png);"));
        Menu_system = new QAction(MainWindow);
        Menu_system->setObjectName(QStringLiteral("Menu_system"));
        Menu_Score = new QAction(MainWindow);
        Menu_Score->setObjectName(QStringLiteral("Menu_Score"));
        Menu_print = new QAction(MainWindow);
        Menu_print->setObjectName(QStringLiteral("Menu_print"));
        Menu_add_student = new QAction(MainWindow);
        Menu_add_student->setObjectName(QStringLiteral("Menu_add_student"));
        Menu_delete_student = new QAction(MainWindow);
        Menu_delete_student->setObjectName(QStringLiteral("Menu_delete_student"));
        Menu_change_student = new QAction(MainWindow);
        Menu_change_student->setObjectName(QStringLiteral("Menu_change_student"));
        Menu_find_student = new QAction(MainWindow);
        Menu_find_student->setObjectName(QStringLiteral("Menu_find_student"));
        Menu_add_course = new QAction(MainWindow);
        Menu_add_course->setObjectName(QStringLiteral("Menu_add_course"));
        Menu_delete_course = new QAction(MainWindow);
        Menu_delete_course->setObjectName(QStringLiteral("Menu_delete_course"));
        Menu_change_course = new QAction(MainWindow);
        Menu_change_course->setObjectName(QStringLiteral("Menu_change_course"));
        Menu_find_course = new QAction(MainWindow);
        Menu_find_course->setObjectName(QStringLiteral("Menu_find_course"));
        Menu_exit = new QAction(MainWindow);
        Menu_exit->setObjectName(QStringLiteral("Menu_exit"));
        File_save = new QAction(MainWindow);
        File_save->setObjectName(QStringLiteral("File_save"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        stackedWidget = new QStackedWidget(centralWidget);
        stackedWidget->setObjectName(QStringLiteral("stackedWidget"));
        stackedWidget->setGeometry(QRect(0, 0, 521, 431));
        stackedWidget->setAutoFillBackground(true);
        page = new QWidget();
        page->setObjectName(QStringLiteral("page"));
        Registerwidget = new QWidget(page);
        Registerwidget->setObjectName(QStringLiteral("Registerwidget"));
        Registerwidget->setGeometry(QRect(0, 0, 521, 411));
        label = new QLabel(Registerwidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(120, 120, 72, 15));
        label_2 = new QLabel(Registerwidget);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(120, 170, 72, 15));
        Register_idLineEdit = new QLineEdit(Registerwidget);
        Register_idLineEdit->setObjectName(QStringLiteral("Register_idLineEdit"));
        Register_idLineEdit->setGeometry(QRect(210, 120, 113, 21));
        Register_passwardLineEdit = new QLineEdit(Registerwidget);
        Register_passwardLineEdit->setObjectName(QStringLiteral("Register_passwardLineEdit"));
        Register_passwardLineEdit->setGeometry(QRect(210, 170, 113, 21));
        Register_passwardLineEdit->setEchoMode(QLineEdit::Password);
        label_3 = new QLabel(Registerwidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(120, 220, 72, 15));
        Register_checkedWard_lineEdit = new QLineEdit(Registerwidget);
        Register_checkedWard_lineEdit->setObjectName(QStringLiteral("Register_checkedWard_lineEdit"));
        Register_checkedWard_lineEdit->setGeometry(QRect(210, 220, 113, 21));
        Register_checkedWard_lineEdit->setEchoMode(QLineEdit::Password);
        btn_Register_checked = new QPushButton(Registerwidget);
        btn_Register_checked->setObjectName(QStringLiteral("btn_Register_checked"));
        btn_Register_checked->setGeometry(QRect(110, 280, 93, 28));
        btn_Register_checked->setAutoDefault(true);
        btn_register_return = new QPushButton(Registerwidget);
        btn_register_return->setObjectName(QStringLiteral("btn_register_return"));
        btn_register_return->setGeometry(QRect(230, 280, 93, 28));
        btn_register_return->setAutoDefault(true);
        stackedWidget->addWidget(page);
        page_2 = new QWidget();
        page_2->setObjectName(QStringLiteral("page_2"));
        Loginwidget = new QWidget(page_2);
        Loginwidget->setObjectName(QStringLiteral("Loginwidget"));
        Loginwidget->setGeometry(QRect(10, 20, 531, 431));
        Login_idLineEdit = new QLineEdit(Loginwidget);
        Login_idLineEdit->setObjectName(QStringLiteral("Login_idLineEdit"));
        Login_idLineEdit->setGeometry(QRect(240, 120, 113, 21));
        Login_passwardLineEdit = new QLineEdit(Loginwidget);
        Login_passwardLineEdit->setObjectName(QStringLiteral("Login_passwardLineEdit"));
        Login_passwardLineEdit->setGeometry(QRect(240, 180, 113, 21));
        Login_passwardLineEdit->setEchoMode(QLineEdit::Password);
        idLabel = new QLabel(Loginwidget);
        idLabel->setObjectName(QStringLiteral("idLabel"));
        idLabel->setGeometry(QRect(140, 120, 72, 15));
        passwardLabel = new QLabel(Loginwidget);
        passwardLabel->setObjectName(QStringLiteral("passwardLabel"));
        passwardLabel->setGeometry(QRect(140, 180, 72, 15));
        btn_login = new QPushButton(Loginwidget);
        btn_login->setObjectName(QStringLiteral("btn_login"));
        btn_login->setGeometry(QRect(130, 250, 93, 28));
        btn_login->setAutoDefault(true);
        btn_register = new QPushButton(Loginwidget);
        btn_register->setObjectName(QStringLiteral("btn_register"));
        btn_register->setGeometry(QRect(260, 250, 93, 28));
        btn_register->setAutoDefault(true);
        stackedWidget->addWidget(page_2);
        page_3 = new QWidget();
        page_3->setObjectName(QStringLiteral("page_3"));
        Systemwidget = new QWidget(page_3);
        Systemwidget->setObjectName(QStringLiteral("Systemwidget"));
        Systemwidget->setGeometry(QRect(10, 20, 531, 411));
        btn_addstudent = new QPushButton(Systemwidget);
        btn_addstudent->setObjectName(QStringLiteral("btn_addstudent"));
        btn_addstudent->setGeometry(QRect(180, 70, 93, 28));
        btn_addstudent->setAutoDefault(true);
        btn_deletestudent = new QPushButton(Systemwidget);
        btn_deletestudent->setObjectName(QStringLiteral("btn_deletestudent"));
        btn_deletestudent->setGeometry(QRect(180, 120, 93, 28));
        btn_deletestudent->setAutoDefault(true);
        btn_changepassward = new QPushButton(Systemwidget);
        btn_changepassward->setObjectName(QStringLiteral("btn_changepassward"));
        btn_changepassward->setGeometry(QRect(180, 170, 93, 28));
        btn_changepassward->setAutoDefault(true);
        btn_SystemReturnToLogin = new QPushButton(Systemwidget);
        btn_SystemReturnToLogin->setObjectName(QStringLiteral("btn_SystemReturnToLogin"));
        btn_SystemReturnToLogin->setGeometry(QRect(180, 220, 93, 28));
        btn_SystemReturnToLogin->setAutoDefault(true);
        stackedWidget->addWidget(page_3);
        page_4 = new QWidget();
        page_4->setObjectName(QStringLiteral("page_4"));
        label_17 = new QLabel(page_4);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(120, 60, 72, 15));
        Course_id_comboBox = new QComboBox(page_4);
        Course_id_comboBox->setObjectName(QStringLiteral("Course_id_comboBox"));
        Course_id_comboBox->setGeometry(QRect(220, 50, 87, 22));
        label_18 = new QLabel(page_4);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(120, 100, 72, 15));
        Course_name_label = new QLabel(page_4);
        Course_name_label->setObjectName(QStringLiteral("Course_name_label"));
        Course_name_label->setGeometry(QRect(220, 100, 72, 15));
        label_20 = new QLabel(page_4);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(120, 140, 72, 15));
        Course_class_label = new QLabel(page_4);
        Course_class_label->setObjectName(QStringLiteral("Course_class_label"));
        Course_class_label->setGeometry(QRect(220, 140, 72, 15));
        label_22 = new QLabel(page_4);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(120, 180, 72, 15));
        Course_select_comboBox = new QComboBox(page_4);
        Course_select_comboBox->setObjectName(QStringLiteral("Course_select_comboBox"));
        Course_select_comboBox->setGeometry(QRect(220, 180, 87, 22));
        btn_Course_checked = new QPushButton(page_4);
        btn_Course_checked->setObjectName(QStringLiteral("btn_Course_checked"));
        btn_Course_checked->setGeometry(QRect(160, 260, 93, 28));
        stackedWidget->addWidget(page_4);
        page_5 = new QWidget();
        page_5->setObjectName(QStringLiteral("page_5"));
        label_4 = new QLabel(page_5);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(70, 70, 72, 15));
        label_5 = new QLabel(page_5);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(70, 120, 72, 15));
        label_6 = new QLabel(page_5);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(70, 170, 72, 15));
        label_7 = new QLabel(page_5);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(70, 220, 72, 15));
        Addstudnet_id_LineEdit = new QLineEdit(page_5);
        Addstudnet_id_LineEdit->setObjectName(QStringLiteral("Addstudnet_id_LineEdit"));
        Addstudnet_id_LineEdit->setGeometry(QRect(170, 70, 113, 21));
        Addstudent_name_LineEdit = new QLineEdit(page_5);
        Addstudent_name_LineEdit->setObjectName(QStringLiteral("Addstudent_name_LineEdit"));
        Addstudent_name_LineEdit->setGeometry(QRect(170, 120, 113, 21));
        Addstudent_sex_LineEdit = new QLineEdit(page_5);
        Addstudent_sex_LineEdit->setObjectName(QStringLiteral("Addstudent_sex_LineEdit"));
        Addstudent_sex_LineEdit->setGeometry(QRect(170, 170, 113, 21));
        Addstudent_class_LineEdit = new QLineEdit(page_5);
        Addstudent_class_LineEdit->setObjectName(QStringLiteral("Addstudent_class_LineEdit"));
        Addstudent_class_LineEdit->setGeometry(QRect(170, 220, 113, 21));
        btn_student_add = new QPushButton(page_5);
        btn_student_add->setObjectName(QStringLiteral("btn_student_add"));
        btn_student_add->setGeometry(QRect(350, 90, 93, 28));
        btn_student_add->setAutoDefault(true);
        stackedWidget->addWidget(page_5);
        page_6 = new QWidget();
        page_6->setObjectName(QStringLiteral("page_6"));
        label_8 = new QLabel(page_6);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(70, 70, 72, 15));
        label_9 = new QLabel(page_6);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(70, 130, 72, 15));
        label_10 = new QLabel(page_6);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(70, 180, 72, 15));
        label_11 = new QLabel(page_6);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(70, 240, 72, 15));
        Find_student_nameLabel = new QLabel(page_6);
        Find_student_nameLabel->setObjectName(QStringLiteral("Find_student_nameLabel"));
        Find_student_nameLabel->setGeometry(QRect(190, 130, 72, 15));
        Find_student_sexLabel = new QLabel(page_6);
        Find_student_sexLabel->setObjectName(QStringLiteral("Find_student_sexLabel"));
        Find_student_sexLabel->setGeometry(QRect(190, 180, 72, 15));
        Find_student_classLabel = new QLabel(page_6);
        Find_student_classLabel->setObjectName(QStringLiteral("Find_student_classLabel"));
        Find_student_classLabel->setGeometry(QRect(190, 240, 72, 15));
        btn_Find_student = new QPushButton(page_6);
        btn_Find_student->setObjectName(QStringLiteral("btn_Find_student"));
        btn_Find_student->setGeometry(QRect(100, 310, 93, 28));
        Find_student_comboBox = new QComboBox(page_6);
        Find_student_comboBox->setObjectName(QStringLiteral("Find_student_comboBox"));
        Find_student_comboBox->setGeometry(QRect(180, 70, 87, 22));
        stackedWidget->addWidget(page_6);
        page_7 = new QWidget();
        page_7->setObjectName(QStringLiteral("page_7"));
        delete_student_comboBox = new QComboBox(page_7);
        delete_student_comboBox->setObjectName(QStringLiteral("delete_student_comboBox"));
        delete_student_comboBox->setGeometry(QRect(240, 120, 87, 22));
        label_12 = new QLabel(page_7);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(130, 120, 72, 15));
        btn_student_delete = new QPushButton(page_7);
        btn_student_delete->setObjectName(QStringLiteral("btn_student_delete"));
        btn_student_delete->setGeometry(QRect(180, 250, 93, 28));
        stackedWidget->addWidget(page_7);
        page_8 = new QWidget();
        page_8->setObjectName(QStringLiteral("page_8"));
        label_13 = new QLabel(page_8);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(100, 80, 72, 15));
        change_student_comboBox = new QComboBox(page_8);
        change_student_comboBox->setObjectName(QStringLiteral("change_student_comboBox"));
        change_student_comboBox->setGeometry(QRect(220, 70, 87, 22));
        label_14 = new QLabel(page_8);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(100, 130, 72, 15));
        label_15 = new QLabel(page_8);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(100, 180, 72, 15));
        label_16 = new QLabel(page_8);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(100, 230, 72, 15));
        change_student_namelineEdit = new QLineEdit(page_8);
        change_student_namelineEdit->setObjectName(QStringLiteral("change_student_namelineEdit"));
        change_student_namelineEdit->setGeometry(QRect(220, 130, 113, 21));
        change_student_sexlineEdit = new QLineEdit(page_8);
        change_student_sexlineEdit->setObjectName(QStringLiteral("change_student_sexlineEdit"));
        change_student_sexlineEdit->setGeometry(QRect(220, 180, 113, 21));
        change_student_classlineEdit = new QLineEdit(page_8);
        change_student_classlineEdit->setObjectName(QStringLiteral("change_student_classlineEdit"));
        change_student_classlineEdit->setGeometry(QRect(220, 230, 113, 21));
        btn_change_student = new QPushButton(page_8);
        btn_change_student->setObjectName(QStringLiteral("btn_change_student"));
        btn_change_student->setGeometry(QRect(160, 300, 93, 28));
        stackedWidget->addWidget(page_8);
        page_9 = new QWidget();
        page_9->setObjectName(QStringLiteral("page_9"));
        label_19 = new QLabel(page_9);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(110, 70, 72, 15));
        label_21 = new QLabel(page_9);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(110, 110, 72, 15));
        label_23 = new QLabel(page_9);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(110, 150, 72, 15));
        label_24 = new QLabel(page_9);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(110, 190, 72, 15));
        Course_delete_idcomboBox = new QComboBox(page_9);
        Course_delete_idcomboBox->setObjectName(QStringLiteral("Course_delete_idcomboBox"));
        Course_delete_idcomboBox->setGeometry(QRect(210, 60, 87, 22));
        Course_delete_namelabel = new QLabel(page_9);
        Course_delete_namelabel->setObjectName(QStringLiteral("Course_delete_namelabel"));
        Course_delete_namelabel->setGeometry(QRect(210, 110, 72, 15));
        Course_delete_classlabel = new QLabel(page_9);
        Course_delete_classlabel->setObjectName(QStringLiteral("Course_delete_classlabel"));
        Course_delete_classlabel->setGeometry(QRect(210, 150, 72, 15));
        Course_delete_selectcomboBox = new QComboBox(page_9);
        Course_delete_selectcomboBox->setObjectName(QStringLiteral("Course_delete_selectcomboBox"));
        Course_delete_selectcomboBox->setGeometry(QRect(210, 190, 87, 22));
        btn_course_delete = new QPushButton(page_9);
        btn_course_delete->setObjectName(QStringLiteral("btn_course_delete"));
        btn_course_delete->setGeometry(QRect(160, 260, 93, 28));
        stackedWidget->addWidget(page_9);
        page_11 = new QWidget();
        page_11->setObjectName(QStringLiteral("page_11"));
        label_25 = new QLabel(page_11);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(50, 50, 72, 15));
        Course_Find_comboBox = new QComboBox(page_11);
        Course_Find_comboBox->setObjectName(QStringLiteral("Course_Find_comboBox"));
        Course_Find_comboBox->setGeometry(QRect(140, 40, 87, 22));
        btn_Course_Find = new QPushButton(page_11);
        btn_Course_Find->setObjectName(QStringLiteral("btn_Course_Find"));
        btn_Course_Find->setGeometry(QRect(370, 40, 93, 28));
        label_26 = new QLabel(page_11);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(100, 120, 72, 15));
        label_27 = new QLabel(page_11);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(100, 170, 72, 15));
        label_28 = new QLabel(page_11);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(100, 220, 72, 15));
        label_29 = new QLabel(page_11);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(100, 270, 72, 15));
        Course_Find_label_highmath = new QLabel(page_11);
        Course_Find_label_highmath->setObjectName(QStringLiteral("Course_Find_label_highmath"));
        Course_Find_label_highmath->setGeometry(QRect(210, 120, 72, 15));
        Course_Find_label_posmath = new QLabel(page_11);
        Course_Find_label_posmath->setObjectName(QStringLiteral("Course_Find_label_posmath"));
        Course_Find_label_posmath->setGeometry(QRect(210, 170, 72, 15));
        Course_Find_label_linearMath = new QLabel(page_11);
        Course_Find_label_linearMath->setObjectName(QStringLiteral("Course_Find_label_linearMath"));
        Course_Find_label_linearMath->setGeometry(QRect(210, 220, 72, 15));
        Course_Find_label_discreteMath = new QLabel(page_11);
        Course_Find_label_discreteMath->setObjectName(QStringLiteral("Course_Find_label_discreteMath"));
        Course_Find_label_discreteMath->setGeometry(QRect(210, 270, 72, 15));
        label_34 = new QLabel(page_11);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(320, 120, 72, 15));
        label_35 = new QLabel(page_11);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(320, 170, 72, 15));
        label_36 = new QLabel(page_11);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(320, 220, 72, 15));
        Course_Find_label_cplus2 = new QLabel(page_11);
        Course_Find_label_cplus2->setObjectName(QStringLiteral("Course_Find_label_cplus2"));
        Course_Find_label_cplus2->setGeometry(QRect(420, 120, 72, 15));
        Course_Find_label_java = new QLabel(page_11);
        Course_Find_label_java->setObjectName(QStringLiteral("Course_Find_label_java"));
        Course_Find_label_java->setGeometry(QRect(420, 170, 72, 15));
        Course_Find_label_python = new QLabel(page_11);
        Course_Find_label_python->setObjectName(QStringLiteral("Course_Find_label_python"));
        Course_Find_label_python->setGeometry(QRect(420, 220, 72, 15));
        stackedWidget->addWidget(page_11);
        page_12 = new QWidget();
        page_12->setObjectName(QStringLiteral("page_12"));
        label_30 = new QLabel(page_12);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(50, 30, 72, 15));
        Score_id_comboBox = new QComboBox(page_12);
        Score_id_comboBox->setObjectName(QStringLiteral("Score_id_comboBox"));
        Score_id_comboBox->setGeometry(QRect(160, 20, 87, 22));
        label_31 = new QLabel(page_12);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(50, 80, 72, 15));
        Score_name_label = new QLabel(page_12);
        Score_name_label->setObjectName(QStringLiteral("Score_name_label"));
        Score_name_label->setGeometry(QRect(160, 80, 72, 15));
        label_33 = new QLabel(page_12);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(50, 130, 72, 15));
        Score_class_label = new QLabel(page_12);
        Score_class_label->setObjectName(QStringLiteral("Score_class_label"));
        Score_class_label->setGeometry(QRect(160, 130, 72, 15));
        label_38 = new QLabel(page_12);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(50, 180, 72, 15));
        Score_lineEdit_highMath = new QLineEdit(page_12);
        Score_lineEdit_highMath->setObjectName(QStringLiteral("Score_lineEdit_highMath"));
        Score_lineEdit_highMath->setGeometry(QRect(150, 170, 113, 21));
        label_39 = new QLabel(page_12);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(50, 220, 72, 15));
        Score_lineEdit_posMath = new QLineEdit(page_12);
        Score_lineEdit_posMath->setObjectName(QStringLiteral("Score_lineEdit_posMath"));
        Score_lineEdit_posMath->setGeometry(QRect(150, 210, 113, 21));
        label_40 = new QLabel(page_12);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(50, 260, 72, 15));
        Score_lineEdit_linearMath = new QLineEdit(page_12);
        Score_lineEdit_linearMath->setObjectName(QStringLiteral("Score_lineEdit_linearMath"));
        Score_lineEdit_linearMath->setGeometry(QRect(150, 250, 113, 21));
        label_41 = new QLabel(page_12);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(50, 300, 72, 15));
        Score_lineEdit_discreteMath = new QLineEdit(page_12);
        Score_lineEdit_discreteMath->setObjectName(QStringLiteral("Score_lineEdit_discreteMath"));
        Score_lineEdit_discreteMath->setGeometry(QRect(150, 290, 113, 21));
        label_42 = new QLabel(page_12);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(300, 180, 72, 15));
        Score_lineEdit_cplus2 = new QLineEdit(page_12);
        Score_lineEdit_cplus2->setObjectName(QStringLiteral("Score_lineEdit_cplus2"));
        Score_lineEdit_cplus2->setGeometry(QRect(370, 170, 113, 21));
        label_43 = new QLabel(page_12);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(300, 210, 72, 15));
        Score_lineEdit_java = new QLineEdit(page_12);
        Score_lineEdit_java->setObjectName(QStringLiteral("Score_lineEdit_java"));
        Score_lineEdit_java->setGeometry(QRect(370, 210, 113, 21));
        label_44 = new QLabel(page_12);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(290, 250, 72, 15));
        Score_lineEdit_python = new QLineEdit(page_12);
        Score_lineEdit_python->setObjectName(QStringLiteral("Score_lineEdit_python"));
        Score_lineEdit_python->setGeometry(QRect(370, 250, 113, 21));
        stackedWidget->addWidget(page_12);
        page_10 = new QWidget();
        page_10->setObjectName(QStringLiteral("page_10"));
        stackedWidget->addWidget(page_10);
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 534, 26));
        menu = new QMenu(menuBar);
        menu->setObjectName(QStringLiteral("menu"));
        Menu_Student = new QMenu(menu);
        Menu_Student->setObjectName(QStringLiteral("Menu_Student"));
        Menu_course = new QMenu(menu);
        Menu_course->setObjectName(QStringLiteral("Menu_course"));
        menu_2 = new QMenu(menuBar);
        menu_2->setObjectName(QStringLiteral("menu_2"));
        MainWindow->setMenuBar(menuBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);

        menuBar->addAction(menu->menuAction());
        menuBar->addAction(menu_2->menuAction());
        menu->addAction(Menu_system);
        menu->addAction(Menu_Score);
        menu->addAction(Menu_Student->menuAction());
        menu->addAction(Menu_course->menuAction());
        menu->addAction(Menu_print);
        menu->addAction(Menu_exit);
        Menu_Student->addAction(Menu_add_student);
        Menu_Student->addAction(Menu_delete_student);
        Menu_Student->addAction(Menu_change_student);
        Menu_Student->addAction(Menu_find_student);
        Menu_course->addAction(Menu_add_course);
        Menu_course->addAction(Menu_delete_course);
        Menu_course->addAction(Menu_change_course);
        Menu_course->addAction(Menu_find_course);
        menu_2->addAction(File_save);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(1);
        btn_Register_checked->setDefault(false);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "\345\255\246\347\261\215\347\256\241\347\220\206\347\263\273\347\273\237", Q_NULLPTR));
        Menu_system->setText(QApplication::translate("MainWindow", "\347\263\273\347\273\237\347\256\241\347\220\206", Q_NULLPTR));
        Menu_Score->setText(QApplication::translate("MainWindow", "\346\210\220\347\273\251\347\256\241\347\220\206", Q_NULLPTR));
        Menu_print->setText(QApplication::translate("MainWindow", "\346\211\223\345\215\260", Q_NULLPTR));
        Menu_add_student->setText(QApplication::translate("MainWindow", "\346\267\273\345\212\240\345\255\246\347\224\237", Q_NULLPTR));
        Menu_delete_student->setText(QApplication::translate("MainWindow", "\345\210\240\351\231\244\345\255\246\347\224\237", Q_NULLPTR));
        Menu_change_student->setText(QApplication::translate("MainWindow", "\346\233\264\346\224\271\345\255\246\347\224\237\344\277\241\346\201\257", Q_NULLPTR));
        Menu_find_student->setText(QApplication::translate("MainWindow", "\346\237\245\350\257\242\345\255\246\347\224\237", Q_NULLPTR));
        Menu_add_course->setText(QApplication::translate("MainWindow", "\351\200\211\350\257\276", Q_NULLPTR));
        Menu_delete_course->setText(QApplication::translate("MainWindow", "\351\200\200\350\257\276", Q_NULLPTR));
        Menu_change_course->setText(QApplication::translate("MainWindow", "\346\233\264\346\224\271\350\257\276\347\250\213", Q_NULLPTR));
        Menu_find_course->setText(QApplication::translate("MainWindow", "\346\237\245\350\257\242", Q_NULLPTR));
        Menu_exit->setText(QApplication::translate("MainWindow", "\351\200\200\345\207\272\347\231\273\345\275\225", Q_NULLPTR));
        File_save->setText(QApplication::translate("MainWindow", "\344\277\235\345\255\230\346\226\207\344\273\266", Q_NULLPTR));
        label->setText(QApplication::translate("MainWindow", "\347\224\250\346\210\267\345\220\215", Q_NULLPTR));
        label_2->setText(QApplication::translate("MainWindow", "\345\257\206\347\240\201", Q_NULLPTR));
        label_3->setText(QApplication::translate("MainWindow", "\347\241\256\350\256\244\345\257\206\347\240\201", Q_NULLPTR));
        btn_Register_checked->setText(QApplication::translate("MainWindow", "\346\263\250\345\206\214", Q_NULLPTR));
        btn_register_return->setText(QApplication::translate("MainWindow", "\350\277\224\345\233\236", Q_NULLPTR));
        idLabel->setText(QApplication::translate("MainWindow", "\347\224\250\346\210\267\345\220\215", Q_NULLPTR));
        passwardLabel->setText(QApplication::translate("MainWindow", "\345\257\206\347\240\201", Q_NULLPTR));
        btn_login->setText(QApplication::translate("MainWindow", "\347\231\273\345\275\225", Q_NULLPTR));
        btn_register->setText(QApplication::translate("MainWindow", "\346\263\250\345\206\214", Q_NULLPTR));
        btn_addstudent->setText(QApplication::translate("MainWindow", "\346\267\273\345\212\240\347\224\250\346\210\267", Q_NULLPTR));
        btn_deletestudent->setText(QApplication::translate("MainWindow", "\345\210\240\351\231\244\347\224\250\346\210\267", Q_NULLPTR));
        btn_changepassward->setText(QApplication::translate("MainWindow", "\346\233\264\346\224\271\345\257\206\347\240\201", Q_NULLPTR));
        btn_SystemReturnToLogin->setText(QApplication::translate("MainWindow", "\350\277\224\345\233\236\347\225\214\351\235\242", Q_NULLPTR));
        label_17->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\255\246\345\217\267", Q_NULLPTR));
        label_18->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\247\223\345\220\215", Q_NULLPTR));
        Course_name_label->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        label_20->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\347\217\255\347\272\247", Q_NULLPTR));
        Course_class_label->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        label_22->setText(QApplication::translate("MainWindow", "\351\200\211\350\257\276\350\257\276\347\250\213", Q_NULLPTR));
        btn_Course_checked->setText(QApplication::translate("MainWindow", "\347\241\256\345\256\232", Q_NULLPTR));
        label_4->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\255\246\345\217\267", Q_NULLPTR));
        label_5->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\247\223\345\220\215", Q_NULLPTR));
        label_6->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\346\200\247\345\210\253", Q_NULLPTR));
        label_7->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\347\217\255\347\272\247", Q_NULLPTR));
        btn_student_add->setText(QApplication::translate("MainWindow", "\346\267\273\345\212\240", Q_NULLPTR));
        label_8->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\255\246\345\217\267", Q_NULLPTR));
        label_9->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\247\223\345\220\215", Q_NULLPTR));
        label_10->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\346\200\247\345\210\253", Q_NULLPTR));
        label_11->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\347\217\255\347\272\247", Q_NULLPTR));
        Find_student_nameLabel->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        Find_student_sexLabel->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        Find_student_classLabel->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        btn_Find_student->setText(QApplication::translate("MainWindow", "\346\237\245\350\257\242", Q_NULLPTR));
        label_12->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\255\246\345\217\267", Q_NULLPTR));
        btn_student_delete->setText(QApplication::translate("MainWindow", "\345\210\240\351\231\244", Q_NULLPTR));
        label_13->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\255\246\345\217\267", Q_NULLPTR));
        label_14->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\247\223\345\220\215", Q_NULLPTR));
        label_15->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\346\200\247\345\210\253", Q_NULLPTR));
        label_16->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\347\217\255\347\272\247", Q_NULLPTR));
        btn_change_student->setText(QApplication::translate("MainWindow", "\346\233\264\346\224\271", Q_NULLPTR));
        label_19->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\255\246\345\217\267", Q_NULLPTR));
        label_21->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\247\223\345\220\215", Q_NULLPTR));
        label_23->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\347\217\255\347\272\247", Q_NULLPTR));
        label_24->setText(QApplication::translate("MainWindow", "\351\200\200\350\257\276\350\257\276\347\250\213", Q_NULLPTR));
        Course_delete_namelabel->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        Course_delete_classlabel->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        btn_course_delete->setText(QApplication::translate("MainWindow", "\347\241\256\345\256\232", Q_NULLPTR));
        label_25->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\255\246\345\217\267", Q_NULLPTR));
        btn_Course_Find->setText(QApplication::translate("MainWindow", "\346\237\245\350\257\242", Q_NULLPTR));
        label_26->setText(QApplication::translate("MainWindow", "\351\253\230\346\225\260", Q_NULLPTR));
        label_27->setText(QApplication::translate("MainWindow", "\346\246\202\347\216\207\350\256\272", Q_NULLPTR));
        label_28->setText(QApplication::translate("MainWindow", "\347\272\277\346\200\247\344\273\243\346\225\260", Q_NULLPTR));
        label_29->setText(QApplication::translate("MainWindow", "\347\246\273\346\225\243\346\225\260\345\255\246", Q_NULLPTR));
        Course_Find_label_highmath->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        Course_Find_label_posmath->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        Course_Find_label_linearMath->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        Course_Find_label_discreteMath->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        label_34->setText(QApplication::translate("MainWindow", "c++", Q_NULLPTR));
        label_35->setText(QApplication::translate("MainWindow", "java", Q_NULLPTR));
        label_36->setText(QApplication::translate("MainWindow", "python", Q_NULLPTR));
        Course_Find_label_cplus2->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        Course_Find_label_java->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        Course_Find_label_python->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        label_30->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\255\246\345\217\267", Q_NULLPTR));
        label_31->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\345\247\223\345\220\215", Q_NULLPTR));
        Score_name_label->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        label_33->setText(QApplication::translate("MainWindow", "\345\255\246\347\224\237\347\217\255\347\272\247", Q_NULLPTR));
        Score_class_label->setText(QApplication::translate("MainWindow", "NULL", Q_NULLPTR));
        label_38->setText(QApplication::translate("MainWindow", "\351\253\230\346\225\260", Q_NULLPTR));
        label_39->setText(QApplication::translate("MainWindow", "\346\246\202\347\216\207\350\256\272", Q_NULLPTR));
        label_40->setText(QApplication::translate("MainWindow", "\347\272\277\346\200\247\344\273\243\346\225\260", Q_NULLPTR));
        label_41->setText(QApplication::translate("MainWindow", "\347\246\273\346\225\243\346\225\260\345\255\246", Q_NULLPTR));
        label_42->setText(QApplication::translate("MainWindow", "c++", Q_NULLPTR));
        label_43->setText(QApplication::translate("MainWindow", "java", Q_NULLPTR));
        label_44->setText(QApplication::translate("MainWindow", "python", Q_NULLPTR));
        menu->setTitle(QApplication::translate("MainWindow", "\350\217\234\345\215\225", Q_NULLPTR));
        Menu_Student->setTitle(QApplication::translate("MainWindow", "\345\255\246\347\224\237\347\256\241\347\220\206", Q_NULLPTR));
        Menu_course->setTitle(QApplication::translate("MainWindow", "\350\257\276\347\250\213\347\256\241\347\220\206", Q_NULLPTR));
        menu_2->setTitle(QApplication::translate("MainWindow", "\346\226\207\344\273\266", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
